apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  - ssh:
      address: homelab-20e3
      user: jmeagher
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller+worker
    noTaints: true
    installFlags:
      - --labels=kubernetes.io/os=linux,kubernetes.io/arch=amd64
  - ssh:
      address: homelab-7502
      user: jmeagher
      port: 22
      keyPath: ~/.ssh/id_rsa
    # noTaints: true
    role: worker
    installFlags:
      - --labels=kubernetes.io/os=linux,kubernetes.io/arch=amd64
  - ssh:
      address: homelab-9be8
      user: jmeagher
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
    # noTaints: true
    installFlags:
      - --labels=kubernetes.io/os=linux,kubernetes.io/arch=amd64
  options:
    wait:
      enabled: true
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 1
      uploads: 5
