repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts

releases:
  - name: alloy-operator
    namespace: grafana
    chart: grafana/alloy-operator
    version: "0.3.4"
    values:
      - values/alloy-operator.yaml
    createNamespace: true
  - name: grafana-k8s-monitoring
    namespace: grafana
    chart: grafana/k8s-monitoring
    version: "3.1.0"
    needs:
    - alloy-operator
    values:
      - values/k8s-monitoring.yaml
    createNamespace: true
  - name: cloudflare-tunnel
    namespace: cloudflare
    chart: ./charts/cloudflare-tunnel
    version: "2025.7.1"
    values:
      - values/cloudflare-tunnel.yaml
    createNamespace: true
