repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts

releases:
  - name: alloy-operator
    namespace: grafana
    chart: grafana/alloy-operator
    version: "0.3.4"
    values:
      - values/alloy-operator.yaml
    createNamespace: true
  - name: grafana-k8s-monitoring
    namespace: grafana
    chart: grafana/k8s-monitoring
    version: "3.1.0"
    needs:
    - alloy-operator
    values:
      - values/k8s-monitoring.yaml
    createNamespace: true
  - name: tailscale-operator
    namespace: tailscale
    chart: tailscale/tailscale-operator
    version: "1.84.2"
    values:
      - values/tailscale-operator.yaml
    createNamespace: true
